name: CI (with Docker Compose)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-stack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run stack with Docker Compose
        run: |
          docker compose up --build -d
          sleep 10  #give time for services to boot
          curl --fail http://localhost:8080/greetings

      - name: Shut down
        run: docker compose down
